services:
  app:
    build: ./docker/php
    container_name: hospital_app
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./shared:/var/www/shared
      - ./.env:/var/www/.env
    environment:
      APP_ENV: "docker"
    depends_on:
      - db
    networks:
      - hospital_net

  nginx:
    image: nginx:latest
    container_name: hospital_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - hospital_net

  db:
    image: mysql:8.0
    container_name: hospital_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospital_system
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - hospital_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: hospital_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - hospital_net

volumes:
  mysql_data:

networks:
  hospital_net:
    driver: bridge
